# Generated by Django 4.2 on 2025-05-30 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likebbs', '0002_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('genre', models.CharField(choices=[('tech', 'テクノロジー'), ('business', 'ビジネス'), ('lifestyle', 'ライフスタイル'), ('entertainment', 'エンターテイメント'), ('sports', 'スポーツ'), ('education', '教育'), ('travel', '旅行'), ('food', '食べ物'), ('health', '健康'), ('other', 'その他')], default='other', max_length=20, verbose_name='ジャンル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='article',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
